-- MySQL Script generated by MySQL Workbench
-- Fri May 24 11:13:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prak` DEFAULT CHARACTER SET utf8 ;
USE `prak` ;

-- -----------------------------------------------------
-- Table `prak`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `photo_file` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_user_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `prak`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`shirt_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`shirt_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `shirt_status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shirt_status_id`),
  INDEX `fk_shift_shirt_status1_idx` (`shirt_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_shift_shirt_status1`
    FOREIGN KEY (`shirt_status_id`)
    REFERENCES `prak`.`shirt_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`user_to_shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`user_to_shift` (
  `user_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `shift_id`),
  INDEX `fk_user_has_shift_shift1_idx` (`shift_id` ASC) VISIBLE,
  INDEX `fk_user_has_shift_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_shift_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prak`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_shift_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `prak`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_status_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_status_id`, `shift_id`, `user_id`),
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  INDEX `fk_order_shift1_idx` (`shift_id` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `prak`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `prak`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prak`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prak`.`order_to_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prak`.`order_to_position` (
  `order_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `position_id`),
  INDEX `fk_order_has_position_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_order_has_position_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_position_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `prak`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_position_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `prak`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
